


import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 
import java.util.Scanner;
  
public class sha1 { 
    
    public static String encryptThisString(String input) 
    { 
        try { 
            
            	MessageDigest md = MessageDigest.getInstance("SHA-1"); 
            	byte[] messageDigest = md.digest(input.getBytes()); 
            	BigInteger no = new BigInteger(1, messageDigest); 
            	String hashtext = no.toString(16); 
            	
            	while (hashtext.length() < 32) 
            	{ 
                	hashtext = "0" + hashtext; 
            	} 
            	
            	return hashtext; 
        }  
        catch (NoSuchAlgorithmException e) 
        { 
            throw new RuntimeException(e); 
        } 
    } 
    
    
    public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
  
        Scanner input=new Scanner(System.in);
        System.out.println("HashCode Generated by SHA-1 for: "); 
 	String s1=input.next(); 
         
        System.out.println("\n" + s1 + " : " + encryptThisString(s1)); 
    } 
} 

/*
Output:
a3-402-09@a3-402-09:~/Desktop$ javac SHA1.java
a3-402-09@a3-402-09:~/Desktop$ java SHA1
HashCode Generated by SHA-1 for: 
nimisha

nimisha : 5dc23f78c07728621b33ccdd0f76246c523a7d98
madhuri

madhuri : fab9d9234981502c652e63cd8599d5a9e099eee6

*/
