library(plyr)
library(arules)
library(arulesViz)
data_csv = read.csv('OnlineRetail.csv')
items = ddply(data_csv,c("InvoiceNo"), function(x)paste(x$Description, collapse = ","))
names(items)=c('Invoice_no','Description')
dataset=data.frame(items$Description)
write.table(dataset,"Items_List.csv",quote=FALSE,row.names = FALSE,col.names=FALSE,sep=",")
baskets = read.transactions("Items_List.csv",rm.duplicates = TRUE,sep=",")
summary(baskets)
itemFrequencyPlot(baskets[1:10],topN=2,type="absolute")
rules=apriori(baskets,parameter = list(support=0.005,confidence=0.8,maxlen=3))
inspect(rules)
rules=sort(rules,by="lift",decreasing = TRUE)

inspect(rules[1:10])
plot(rules[1:10],method="graph",engine="htmlwidget")
